## World University Rankings

The project is aiming at analysing data of 3 differents rankings of world universities.  
Data from : https://www.kaggle.com/datasets/mylesoneill/world-university-rankings

### 1. Download and open CSV files

In [1]:
import pandas as pd
import numpy as np

# University Ranking Data
timesData = pd.read_csv("./Data/timesData.csv", sep = ",", header = 0)
shanghaiData = pd.read_csv("./Data/shanghaiData.csv", sep = ",", header = 0)
cwurData = pd.read_csv("./Data/cwurData.csv", sep = ",", header = 0)

# Supplementary Data
education_expenditure = pd.read_csv("./Data/education_expenditure_supplementary_data.csv", sep = ",", header = 0, encoding='ascii')
educational_attainment = pd.read_csv("./Data/educational_attainment_supplementary_data.csv", sep = ",", header = 0)
school_and_country_table = pd.read_csv("./Data/school_and_country_table.csv", sep = ",", header = 0)

### 2. Questions du manager

a. Donne un aperçu de chaque fichier csv et décris en une phrase son contenu.

In [2]:
# Times Higher Education World University Ranking
print('Times Higher Education World University Ranking:')
timesData.head()

Times Higher Education World University Ranking:


world_rank                        university_name                   country  \
0          1                     Harvard University  United States of America   
1          2     California Institute of Technology  United States of America   
2          3  Massachusetts Institute of Technology  United States of America   
3          4                    Stanford University  United States of America   
4          5                   Princeton University  United States of America   

   teaching international  research  citations income total_score  \
0      99.7          72.4      98.7       98.8   34.5        96.1   
1      97.7          54.6      98.0       99.9   83.7        96.0   
2      97.8          82.3      91.4       99.9   87.5        95.6   
3      98.3          29.5      98.1       99.2   64.3        94.3   
4      90.9          70.3      95.4       99.9      -        94.2   

  num_students  student_staff_ratio international_students female_male_ratio  \
0       20,152                  8.9                    25%               NaN   
1        2,243                  6.9                    27%           33 : 67   
2       11,074                  9.0                    33%           37 : 63   
3       15,596                  7.8                    22%           42 : 58   
4        7,929                  8.4                    27%           45 : 55   

   year  
0  2011  
1  2011  
2  2011  
3  2011  
4  2011

In [3]:
# Academic Ranking of World Universities (Shanghai Ranking)
print('Academic Ranking of World Universities (Shanghai Ranking):')
shanghaiData.head()

Academic Ranking of World Universities (Shanghai Ranking):


world_rank                              university_name national_rank  \
0          1                           Harvard University             1   
1          2                      University of Cambridge             1   
2          3                          Stanford University             2   
3          4           University of California, Berkeley             3   
4          5  Massachusetts Institute of Technology (MIT)             4   

   total_score  alumni  award   hici     ns    pub   pcp  year  
0        100.0   100.0  100.0  100.0  100.0  100.0  72.4  2005  
1         73.6    99.8   93.4   53.3   56.6   70.9  66.9  2005  
2         73.4    41.1   72.2   88.5   70.9   72.3  65.0  2005  
3         72.8    71.8   76.0   69.4   73.9   72.2  52.7  2005  
4         70.1    74.0   80.6   66.7   65.8   64.3  53.0  2005

In [4]:
# Center for World University Rankings
print('Center for World University Rankings:')
cwurData.head()

Center for World University Rankings:


world_rank                            institution         country  \
0           1                     Harvard University             USA   
1           2  Massachusetts Institute of Technology             USA   
2           3                    Stanford University             USA   
3           4                University of Cambridge  United Kingdom   
4           5     California Institute of Technology             USA   

   national_rank  quality_of_education  alumni_employment  quality_of_faculty  \
0              1                     7                  9                   1   
1              2                     9                 17                   3   
2              3                    17                 11                   5   
3              1                    10                 24                   4   
4              4                     2                 29                   7   

   publications  influence  citations  broad_impact  patents   score  year  
0             1          1          1           NaN        5  100.00  2012  
1            12          4          4           NaN        1   91.67  2012  
2             4          2          2           NaN       15   89.50  2012  
3            16         16         11           NaN       50   86.17  2012  
4            37         22         22           NaN       18   85.21  2012

In [5]:
# Supplementary Data: Educational attainment
print('Supplementary Data: Educational attainment')
educational_attainment.head()

Supplementary Data: Educational attainment


country_name                                        series_name  1985  1986  \
0  Afghanistan  Barro-Lee: Average years of primary schooling,...  0.33   NaN   
1  Afghanistan  Barro-Lee: Average years of primary schooling,...  1.03   NaN   
2  Afghanistan  Barro-Lee: Average years of primary schooling,...  0.83   NaN   
3  Afghanistan  Barro-Lee: Average years of primary schooling,...  2.34   NaN   
4  Afghanistan  Barro-Lee: Average years of primary schooling,...  0.54   NaN   

   1987  1990  1991  1992  1993  1995  ...  2005  2006  2007  2008  2009  \
0   NaN  0.44   NaN   NaN   NaN  0.57  ...  0.86   NaN   NaN   NaN   NaN   
1   NaN  1.26   NaN   NaN   NaN  1.54  ...  2.18   NaN   NaN   NaN   NaN   
2   NaN  0.95   NaN   NaN   NaN  1.26  ...  1.01   NaN   NaN   NaN   NaN   
3   NaN  2.22   NaN   NaN   NaN  2.37  ...  2.26   NaN   NaN   NaN   NaN   
4   NaN  0.92   NaN   NaN   NaN  0.94  ...  2.00   NaN   NaN   NaN   NaN   

   2010  2011  2012  2013  2015  
0  1.27   NaN   NaN   NaN   NaN  
1  2.64   NaN   NaN   NaN   NaN  
2  2.45   NaN   NaN   NaN   NaN  
3  3.55   NaN   NaN   NaN   NaN  
4  1.29   NaN   NaN   NaN   NaN  

[5 rows x 29 columns]

In [6]:
# Supplementary Data: Education expenditure
print('Supplementary Data: Education expenditure')
# This data set gives the expenses per country, its type (public or private) and year.
# It represents expenditure as a percentage of gross domestic product.
education_expenditure.head()

Supplementary Data: Education expenditure


country     institute_type direct_expenditure_type  1995  2000  2005  \
0  OECD Average  All Institutions                   Public   4.9   4.9   5.0   
1     Australia  All Institutions                   Public   4.5   4.6   4.3   
2       Austria  All Institutions                   Public   5.3   5.4   5.2   
3       Belgium  All Institutions                   Public   5.0   5.1   5.8   
4        Canada  All Institutions                   Public   5.8   5.2   4.8   

   2009  2010  2011  
0   5.4   5.4   5.3  
1   4.5   4.6   4.3  
2   5.7   5.6   5.5  
3   6.4   6.4   6.4  
4   5.0   5.2   NaN

In [7]:
# Supplementary Data: School and country table
print('Supplementary Data: School and country table:')
school_and_country_table.head()

Supplementary Data: School and country table:


school_name                   country
0                     Harvard University  United States of America
1     California Institute of Technology  United States of America
2  Massachusetts Institute of Technology  United States of America
3                    Stanford University  United States of America
4                   Princeton University  United States of America

b) Quelles années sont prises en charge par chaque classement ?


In [8]:
# For timesData
print("Years taken into account for timesData are: ")
print(timesData['year'].unique())

# For shanghaiData
print("Years taken into account for shanghaiData are: ")
print(shanghaiData['year'].unique())

# For cwurData
print("Years taken into account for cwurData are: ")
print(cwurData['year'].unique())

Years taken into account for timesData are: 
[2011 2012 2013 2014 2015 2016]
Years taken into account for shanghaiData are: 
[2005 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015]
Years taken into account for cwurData are: 
[2012 2013 2014 2015]


c) Combien d'universités sont prises en compte annuellement par chaque classement en moyenne ? Il s'agit ici de donner le nombre moyen d'universités prises en compte par chaque classement lors d'une année.

In [9]:
# For timesData
times_avg_universities = timesData.groupby('year')['world_rank'].count().mean()
print("The average number of universities taken into account each year by timesData is:", times_avg_universities)

# For shanghaiData
shanghai_avg_universities = shanghaiData.groupby('year')['world_rank'].count().mean()
print("The average number of universities taken into account each year by shanghaiData is:", shanghai_avg_universities)

# For cwurData
cwur_avg_universities = cwurData.groupby('year')['world_rank'].count().mean()
print("The average number of universities taken into account each year by cwurData is:", cwur_avg_universities)

The average number of universities taken into account each year by timesData is: 433.8333333333333
The average number of universities taken into account each year by shanghaiData is: 445.1818181818182
The average number of universities taken into account each year by cwurData is: 550.0


d) Quels sont les rankings obtenus par l'Université de Strasbourg dans chacun des 3 classements disponibles ?

In [10]:
# For timesData
times_uni_strasbourg = timesData[timesData['university_name'] == 'University of Strasbourg']
if not times_uni_strasbourg.empty:
    print("University of Strasbourg in timesData:")
    print(times_uni_strasbourg[['year', 'world_rank']])
    print("\n")
else:
    print("University of Strasbourg is not present in timesData.\n")

# For shanghaiData
shanghai_uni_strasbourg = shanghaiData[shanghaiData['university_name'] == 'University of Strasbourg']
if not shanghai_uni_strasbourg.empty:
    print("University of Strasbourg in shanghaiData:")
    print(shanghai_uni_strasbourg[['year', 'world_rank']])
    print("\n")
else:
    print("University of Strasbourg is not present in shanghaiData.\n")

# For cwurData
cwur_uni_strasbourg = cwurData[cwurData['institution'] == 'University of Strasbourg']
if not cwur_uni_strasbourg.empty:
    print("University of Strasbourg in cwurData:")
    print(cwur_uni_strasbourg[['year', 'world_rank']])
    print("\n")
else:
    print("University of Strasbourg is not present in cwurData.\n")

University of Strasbourg in timesData:
      year world_rank
422   2012    201-225
825   2013    201-225
1223  2014    201-225
1619  2015    201-225
2142  2016    301-350


University of Strasbourg in shanghaiData:
      year world_rank
91    2005         92
595   2006         96
1100  2007         99
1656  2008    101-151
2158  2009    101-151
2657  2010    101-150
3157  2011    102-150
3659  2012    101-150
3894  2013         97
3991  2014         95
4485  2015         87


University of Strasbourg in cwurData:
      year  world_rank
375   2014         176
1381  2015         182




e) Selon le classement du Times, quels sont les 20 meilleures universités en 2016 ? Quelle est la part d'universités américaines ?

In [16]:
# Top 20 universities from 2016 in Times ranking
timesData_2016 = timesData[timesData['year'] == 2016]
top_20_times = timesData_2016.sort_values(by='world_rank').head(20)
print(top_20_times[['university_name', 'world_rank']])

# Percentage of top 20 universities that are in the USA
num_usa_universities = top_20_times[top_20_times['country'] == 'United States of America']['country'].count()
percent_usa_universities = (num_usa_universities / 20) * 100
print("Percentage of top 20 universities in 2016 in the USA: ", percent_usa_universities)


                                        university_name  world_rank
1803                 California Institute of Technology         1.0
1804                               University of Oxford         2.0
1805                                Stanford University         3.0
1806                            University of Cambridge         4.0
1807              Massachusetts Institute of Technology         5.0
1808                                 Harvard University         6.0
1809                               Princeton University         7.0
1810                            Imperial College London         8.0
1811  ETH Zurich – Swiss Federal Institute of Techno...         9.0
1812                              University of Chicago        10.0
1813                           Johns Hopkins University        11.0
1814                                    Yale University        12.0
1815                 University of California, Berkeley        13.0
1816                          University College

f) Combien chaque pays possède d'universités dans le classement de Shanghai en 2015 ? Range la liste par ordre décroissant. Pense à t'aider de la table université - pays pour réaliser cette requête.

g) Quelles sont les universités françaises présentes dans le classement du Center for WUR ?

h) Quels pays ont les plus faibles ratios (Dépenses dans les Institutions du Supérieur (Privées et Publiques) en 2011) / Nombre d'universités dans le classement du Times en 2011 ? Range cette liste par ordre croissant.

### 3. Trouver des informations intéressantes